name: interfract
favicon: null
layout_spectrum: 0.527575850719586
typography_spectrum: 0.45559638109989464
title: interfracting the grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.990862988634035
  lightness: 0.11154019110836089
  saturation: 0.19982848805375397
  rhythmicContrast: 0.22944789589382708
purpose: []
